apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: group4-the-best-group-4-project
  app.kubernetes.io/instance: group4-the-best-group-4-project-instance
  app.kubernetes.io/name: group4-the-best-group-4-project
images:
- name: quay.io/alex_best_ibm/the-best-group-4-project
  newName: quay.io/alex_best_ibm/the-best-group-4-project
  newTag: 9bc300f48baedfb9c92b897a009c7c3cc01bbdeb
  ## NEED TO FIND OUT WAT THIS TAG IS 
